# https://github.com/actions/setup-dotnet
steps:
- uses: actions/checkout@master
- uses: actions/setup-dotnet@v1
  with:
    dotnet-version: '3.1.100' # SDK Version to use.
- run: dotnet .\test\SecureStore.Contrib.Configuration.Tests
